#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : "Manual #LibreMentor"  # The title of the book. Will be placed in the left navbar.
author                      : Jorge Toledo, Carlos Cámara  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo

# Information about where the book exists on the web
repository:
  url: https://github.com/Librementor/librementor-book
   #path_to_book: path/to/your/book  # An optional path to your book, defaults to repo root
  branch: main  # An optional branch, defaults to `master`

html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

# html:
#     extra_navbar: |
#         <div>
#           my html code
#         </div>
